

SELECT * FROM customer_behavior
LIMIT 20

--Q1. what is the toltal revenue generated by Male Vs Female Custmors
select gender, SUM(purchase_amount) as revenue
from customer_behavior
group by gender

--Q2. Customers who used dicount and yet spend more than average on shopping

SELECT customer_id, purchase_amount
FROM customer_behavior
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM customer_behavior
  );

  
--Q3. Top 5 Highest Average Review rating products

 select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Top Average Producr Rating"
 from customer_behavior
 group by item_purchased
 order by avg(review_rating) desc
 limit 5;

 -- Q4. Compare average purchase amount between Standard and Express Shipping
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount::numeric), 2) AS average_purchase_amount
FROM customer_behavior
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5: Do subscribed customers spend more?


SELECT 
    subscription_status,
    ROUND(AVG(purchase_amount::numeric), 2) AS average_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer_behavior
GROUP BY subscription_status;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?



SELECT 
    item_purchased,
    ROUND(
        100.0 * SUM(
            CASE 
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS discount_percentage
FROM customer_behavior
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. "How many New, Returning, and Loyal customers do we have?"


SELECT
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer_behavior
GROUP BY customer_segment
ORDER BY customer_count DESC;


-- Q8 — What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS item_rank
    FROM customer_behavior
    GROUP BY category, item_purchased
)

SELECT
    category,
    item_purchased,
    total_orders,
    item_rank
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;

-- Q9. Are customers who are frequent buyers (more than 5 previous purchases) also more likely to subscribe?
SELECT
    CASE
        WHEN previous_purchases > 5 THEN 'Frequent Buyer'
        ELSE 'Not Frequent Buyer'
    END AS buyer_type,

    COUNT(*) AS total_customers,

    SUM(
        CASE
            WHEN subscription_status = 'Yes' THEN 1
            ELSE 0
        END
    ) AS subscribed_customers,

    ROUND(
        100.0 * SUM(
            CASE
                WHEN subscription_status = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS subscription_rate

FROM customer_behavior

GROUP BY buyer_type;
-- Q10 Which age group contributes the most money to our total revenue, and what percentage of total revenue does each group contribute?
SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue,
    ROUND(
        100.0 * SUM(purchase_amount)
        / SUM(SUM(purchase_amount)) OVER (),
        2
    ) AS revenue_contribution_percentage
FROM customer_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;